package com.srivas.exception;

public enum ErrorsEnum {
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXISTS, INVALID_CREDENTIALS, NO_PROPERTIES, PACKAGE_DOES_NOT_EXISTS, NO_IMAGE_FOUND, VALIDATION_ERROR
}
