const signupFields = [
  {
    labelText: "Name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
  },
  {
    labelText: "Mobile Number",
    id: "mobile",
    name: "mobile",
    type: "mobile",
    autoComplete: "mobile",
    isRequired: true,
    placeholder: "Mobile",
  },
  {
    labelText: "Email address",

    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email",
  },
  {
    labelText: "Password",

    id: "password",
    name: "password",
    type: "password",
    autoComplete: "password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    id: "confirmPassword",
    name: "confirmPassword",
    type: "password",
    autoComplete: "confirmPassword",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

const loginFields = [
  {
    labelText: "Email address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email",
  },
  {
    labelText: "Password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "password",
    isRequired: true,
    placeholder: "Password",
  },
];

const addressFields = [
  {
    labelText: "name",
    id: "name",
    name: "name",
    type: "name",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
  },
  {
    labelText: "houseNumber",
    id: "houseNumber",
    name: "houseNumber",
    type: "houseNumber",
    autoComplete: "houseNumber",
    isRequired: true,
    placeholder: "House Number",
  },
  {
    labelText: "street",
    id: "street",
    name: "street",
    type: "street",
    autoComplete: "street",
    isRequired: true,
    placeholder: "Street",
  },
  {
    labelText: "locality",
    id: "locality",
    name: "locality",
    type: "locality",
    autoComplete: "locality",
    isRequired: true,
    placeholder: "Locality",
  },
  {
    labelText: "landmark",
    id: "landmark",
    name: "landmark",
    type: "landmark",
    autoComplete: "landmark",
    isRequired: true,
    placeholder: "Landmark",
  },
  {
    labelText: "city",
    id: "city",
    name: "city",
    type: "city",
    autoComplete: "city",
    isRequired: true,
    placeholder: "City",
  },
  {
    labelText: "state",
    id: "state",
    name: "state",
    type: "state",
    autoComplete: "state",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "pincode",
    id: "pincode",
    name: "pincode",
    type: "pincode",
    autoComplete: "pincode",
    isRequired: true,
    placeholder: "Pincode",
  },
];

const propertyFields = [
  {
    labelText: "Title",
    id: "shortDescription",
    name: "shortDescription",
    type: "text",
    autoComplete: "shortDescription",
    isRequired: true,
    placeholder: "Title",
  },
  {
    labelText: "Rent",
    id: "rent",
    name: "rent",
    type: "rent",
    autoComplete: "rent",
    isRequired: true,
    placeholder: "Rent",
  },
  {
    labelText: "Deposit",
    id: "deposit",
    name: "deposit",
    type: "deposit",
    autoComplete: "deposit",
    isRequired: true,
    placeholder: "Deposit",
  },
  {
    labelText: "AreaSqFt",
    id: "areaSqFt",
    name: "areaSqFt",
    type: "areaSqFt",
    autoComplete: "areaSqFt",
    isRequired: true,
    placeholder: "Area Sq. Ft.",
  },
  {
    labelText: "Bedroom",
    id: "bedroom",
    name: "bedroom",
    type: "bedroom",
    autoComplete: "bedroom",
    isRequired: true,
    placeholder: "Bedroom",
  },
  {
    labelText: "Bathroom",
    id: "bathroom",
    name: "bathroom",
    type: "bathroom",
    autoComplete: "bathroom",
    isRequired: true,
    placeholder: "Bathroom",
  },
  {
    labelText: "Description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: true,
    placeholder: "Description",
  },
];

const propertyFieldsButtons = [
  {
    labelText: "Furnishing Status",
    id: "furnishingStatus",
    name: "furnishingStatus",
    type: "radio",
    autoComplete: "furnishingStatus",
    isRequired: true,
    placeholder: "Furnishing Status",
  },
  {
    labelText: "Gated Security",
    id: "gatedSecurity",
    name: "gatedSecurity",
    type: "radio",
    autoComplete: "gatedSecurity",
    isRequired: true,
    placeholder: "Gated Security",
  },
  {
    labelText: "Parking",
    id: "parking",
    name: "parking",
    type: "checkbox",
    options: [
      { value: "car", label: "Car" },
      { value: "bike", label: "Bike" },
    ],
    isRequired: false,
    placeholder: "Parking",
  },
];

export {
  loginFields,
  signupFields,
  addressFields,
  propertyFields,
  propertyFieldsButtons,
};
